services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports: !override
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-lokiexplore-app
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVER_ROOT_URL: http://localhost:3001/grafana
      GF_PLUGINS_PREINSTALL_DISABLED: true
      GF_FEATURE_TOGGLES_ENABLE: accessControlOnCall lokiLogsDataplane kubernetesLogsDrilldown ${GF_FEATURE_TOGGLES_ENABLE}
      GRAFANA_CLOUD_LOGS_KEY: ${GRAFANA_CLOUD_LOGS_KEY}
